default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") { "mirzalazuardi" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quote_editor_development
test:
  <<: *default
  database: quote_editor_test
production:
  <<: *default
  database: quote_editor_production
  username: quote_editor
  password: <%= ENV["QUOTE_EDITOR_DATABASE_PASSWORD"] %>
